import { config } from 'dotenv';
import fetch, { RequestInit } from 'node-fetch';
import { HttpsProxyAgent } from 'https-proxy-agent';
import { tool, DynamicStructuredTool } from '@langchain/core/tools';
import { getEnvironmentVariable } from '@langchain/core/utils/env';
import type * as t from '@/types';
import { EnvVar, Constants } from '@/common';

config();

export const imageExtRegex = /\.(jpg|jpeg|png|gif|webp)$/i;
export const getCodeBaseURL = (): string =>
  getEnvironmentVariable(EnvVar.CODE_BASEURL) ??
  Constants.OFFICIAL_CODE_BASEURL;

const imageMessage = 'Image is already displayed to the user';
const otherMessage = 'File is already downloaded by the user';
const inheritedFileMessage =
  'Available as an input — already known to the user';
const accessMessage =
  'Note: Files from previous executions are automatically available and can be modified.';
const emptyOutputMessage =
  'stdout: Empty. Ensure you\'re writing output explicitly.\n';
const inheritedFilesHeader =
  'Available files (inputs, not generated by this execution):';
const generatedFilesHeader = 'Generated files:';
const inheritedNote =
  'Note: Files in "Available files" are inputs the user (or a skill) already provided to the sandbox. They were not produced by this execution and you should not present them as new outputs in your response.';

/**
 * Renders one section of the post-execution file listing. Used by the
 * code/bash tool formatters to keep generated outputs and inherited
 * inputs visually separated. See BashExecutor for full docs.
 */
export function renderFileSection(
  header: string,
  files: t.FileRefs,
  defaultMessage: string
): string {
  if (files.length === 0) return '';
  let out = `${header}\n`;
  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const isImage = imageExtRegex.test(file.name);
    out += `- /mnt/data/${file.name} | ${isImage ? imageMessage : defaultMessage}`;
    if (i < files.length - 1) {
      out += files.length <= 3 ? ', ' : ',\n';
    }
  }
  out += '\n';
  return out;
}

const SUPPORTED_LANGUAGES = [
  'py',
  'js',
  'ts',
  'c',
  'cpp',
  'java',
  'php',
  'rs',
  'go',
  'd',
  'f90',
  'r',
  'bash',
] as const;

export const CodeExecutionToolSchema = {
  type: 'object',
  properties: {
    lang: {
      type: 'string',
      enum: SUPPORTED_LANGUAGES,
      description:
        'The programming language or runtime to execute the code in.',
    },
    code: {
      type: 'string',
      description: `The complete, self-contained code to execute, without any truncation or minimization.
- The environment is stateless; variables and imports don't persist between executions.
- Generated files from previous executions are automatically available in "/mnt/data/".
- Files from previous executions are automatically available and can be modified in place.
- Input code **IS ALREADY** displayed to the user, so **DO NOT** repeat it in your response unless asked.
- Output code **IS NOT** displayed to the user, so **DO** write all desired output explicitly.
- IMPORTANT: You MUST explicitly print/output ALL results you want the user to see.
- py: This is not a Jupyter notebook environment. Use \`print()\` for all outputs.
- py: Matplotlib: Use \`plt.savefig()\` to save plots as files.
- js: use the \`console\` or \`process\` methods for all outputs.
- r: IMPORTANT: No X11 display available. ALL graphics MUST use Cairo library (library(Cairo)).
- Other languages: use appropriate output functions.`,
    },
    args: {
      type: 'array',
      items: { type: 'string' },
      description:
        'Additional arguments to execute the code with. This should only be used if the input code requires additional arguments to run.',
    },
  },
  required: ['lang', 'code'],
} as const;

const baseEndpoint = getCodeBaseURL();
const EXEC_ENDPOINT = `${baseEndpoint}/exec`;

type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number];

export const CodeExecutionToolDescription = `
Runs code and returns stdout/stderr output from a stateless execution environment, similar to running scripts in a command-line interface. Each execution is isolated and independent.

Usage:
- No network access available.
- Generated files are automatically delivered; **DO NOT** provide download links.
- NEVER use this tool to execute malicious code.
`.trim();

export const CodeExecutionToolName = Constants.EXECUTE_CODE;

export const CodeExecutionToolDefinition = {
  name: CodeExecutionToolName,
  description: CodeExecutionToolDescription,
  schema: CodeExecutionToolSchema,
} as const;

function createCodeExecutionTool(
  params: t.CodeExecutionToolParams = {}
): DynamicStructuredTool {
  return tool(
    async (rawInput, config) => {
      const { lang, code, ...rest } = rawInput as {
        lang: SupportedLanguage;
        code: string;
        args?: string[];
      };
      /**
       * Extract session context from config.toolCall (injected by ToolNode).
       * - session_id: associates with the previous run.
       * - _injected_files: File refs to pass directly (avoids /files endpoint race condition).
       */
      const { session_id, _injected_files } = (config.toolCall ?? {}) as {
        session_id?: string;
        _injected_files?: t.CodeEnvFile[];
      };

      const postData: Record<string, unknown> = {
        lang,
        code,
        ...rest,
        ...params,
      };

      /**
       * File injection priority:
       * 1. Use _injected_files from ToolNode (avoids /files endpoint race condition)
       * 2. Fall back to fetching from /files endpoint if session_id
       *    provided but no injected files. The /files lookup still uses the
       *    same id value — codeapi stores output files under the exec id as
       *    their storage prefix, so the two values coincide here.
       */
      if (_injected_files && _injected_files.length > 0) {
        postData.files = _injected_files;
      } else if (session_id != null && session_id.length > 0) {
        /** Fallback: fetch from /files endpoint (may have race condition issues) */
        try {
          const filesEndpoint = `${baseEndpoint}/files/${session_id}?detail=full`;
          const fetchOptions: RequestInit = {
            method: 'GET',
            headers: {
              'User-Agent': 'LibreChat/1.0',
            },
          };

          if (process.env.PROXY != null && process.env.PROXY !== '') {
            fetchOptions.agent = new HttpsProxyAgent(process.env.PROXY);
          }

          const response = await fetch(filesEndpoint, fetchOptions);
          if (!response.ok) {
            throw new Error(
              `Failed to fetch files for session: ${response.status}`
            );
          }

          const files = await response.json();
          if (Array.isArray(files) && files.length > 0) {
            const fileReferences: t.CodeEnvFile[] = files.map((file) => {
              const nameParts = file.name.split('/');
              const id = nameParts.length > 1 ? nameParts[1].split('.')[0] : '';

              return {
                storage_session_id: session_id,
                /* `/files` fallback returns code-output files belonging
                 * to the user; tag them user-private. */
                kind: 'user' as const,
                id,
                name: file.metadata['original-filename'],
              };
            });

            postData.files = fileReferences;
          }
        } catch {
          // eslint-disable-next-line no-console
          console.warn(`Failed to fetch files for session: ${session_id}`);
        }
      }

      try {
        const fetchOptions: RequestInit = {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'User-Agent': 'LibreChat/1.0',
          },
          body: JSON.stringify(postData),
        };

        if (process.env.PROXY != null && process.env.PROXY !== '') {
          fetchOptions.agent = new HttpsProxyAgent(process.env.PROXY);
        }
        const response = await fetch(EXEC_ENDPOINT, fetchOptions);
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }

        const result: t.ExecuteResult = await response.json();
        let formattedOutput = '';
        if (result.stdout) {
          formattedOutput += `stdout:\n${result.stdout}\n`;
        } else {
          formattedOutput += emptyOutputMessage;
        }
        if (result.stderr) formattedOutput += `stderr:\n${result.stderr}\n`;
        if (result.files && result.files.length > 0) {
          /* See BashExecutor for the rationale: split inherited (read-only
           * passthrough) inputs from real generated outputs so the LLM
           * doesn't conflate skill files with newly-produced artifacts. */
          const inheritedFiles = result.files.filter(
            (f) => f.inherited === true
          );
          const generatedFiles = result.files.filter(
            (f) => f.inherited !== true
          );

          formattedOutput += renderFileSection(
            generatedFilesHeader,
            generatedFiles,
            otherMessage
          );
          formattedOutput += renderFileSection(
            inheritedFilesHeader,
            inheritedFiles,
            inheritedFileMessage
          );

          if (generatedFiles.length > 0) {
            formattedOutput += `\n\n${accessMessage}`;
          }
          if (inheritedFiles.length > 0) {
            formattedOutput += `\n\n${inheritedNote}`;
          }
          return [
            formattedOutput.trim(),
            {
              session_id: result.session_id,
              files: result.files,
            } satisfies t.CodeExecutionArtifact,
          ];
        }

        return [
          formattedOutput.trim(),
          {
            session_id: result.session_id,
          } satisfies t.CodeExecutionArtifact,
        ];
      } catch (error) {
        throw new Error(
          `Execution error:\n\n${(error as Error | undefined)?.message}`
        );
      }
    },
    {
      name: CodeExecutionToolName,
      description: CodeExecutionToolDescription,
      schema: CodeExecutionToolSchema,
      responseFormat: Constants.CONTENT_AND_ARTIFACT,
    }
  );
}

export { createCodeExecutionTool };
